# notemplating
version: '2'
volumes:
  db:
    driver: rancher-nfs
services:
  web:
    image: registry.gitlab.com/dhiemstra/rancher-scheduler:latest
    restart: always
    environment:
      DATABASE_URL: db:5432/scheduler
    links:
      - db:db
    depends_on:
      - db
  clockwork:
    image: registry.gitlab.com/dhiemstra/rancher-scheduler:latest
    command: clockwork
    restart: always
    environment:
      DATABASE_URL: db:5432/scheduler
    links:
      - db:db
    depends_on:
      - db
    labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environment
  db:
    image: postgres:9.6
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: scheduler
