# notemplating
version: '2'
services:
  # scheduler:
  #   image: registry.gitlab.com/dhiemstra/rancher-scheduler:latest
  #   restart: always
  #   environment:
  #     DATABASE_URL: db:3306/scheduler
  #   links:
  #     - db:db
  #   depends_on:
  #     - db
  #   labels:
  #     io.rancher.sidekicks: clockwork
  clockwork:
    build: .
    command: clockwork
    restart: always
    environment:
      DATABASE_URL: db:5432/scheduler
    volumes:
      - data:/data/bundle
    links:
      - db:db
    depends_on:
      - db
    labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environment
  db:
    image: postgres:9.6
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_DB: scheduler
volumes:
  db: {}
  data: {}
