default: &default
  adapter: postgresql
  encoding: unicode
  username: postgresql
  database: scheduler
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default

production:
  <<: *default
